version: "3"

services:

  api:
    build: .
    ports:
      - "8000:8000"

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: